version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: increase
    commit-message:
      prefix: "update requirements.txt"
    groups:
      python-packages:
        patterns:
          - "*"
    # ignore:
    #   - dependency-name: "numpy"
    #     update-types: [ "version-update:semver-minor" ]
    #   - dependency-name: "pycares"
    #     update-types: [ "version-update:semver-major" ]
